# Generated by Django 3.1.8 on 2022-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0005_auto_20220128_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='when_started',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
